### PR TITLE
Update opac-shelves.tt

### PR DESCRIPTION
**Pull request by Centiljard**

### CODE REVIEW

**Comment by Centiljard** [comment]
Patch preventing script injection in booklist names on  delete confirmation message.

**Comment by kfischer** [comment]
Hi, github is only a mirror for the Koha Community and we are not accepting merge requests. Please find some instructions on how to send patches for Koha in our wiki at https://wiki.koha-community.org/wiki/Submitting_A_Patch. Please let us know if you can submit a patch that way or need help in doing so.

**Comment by Centiljard** [comment]
> Hi, github is only a mirror for the Koha Community and we are not accepting merge requests. Please find some instructions on how to send patches for Koha in our wiki at https://wiki.koha-community.org/wiki/Submitting_A_Patch. Please let us know if you can submit a patch that way or need help in doing so.

Thank you. I’m sure I’ll be able to figure it out.

**Comment by minusdavid** [comment]
We already have a report and fix for this, which should be coming out in the next security release, but thanks for getting in touch.

**Pull request closed without merging**
