### PR TITLE
Fix README.md

### PR DESCRIPTION
**Pull request by phavel**

### CODE REVIEW

**Comment by ranginui** [comment]
Github is used purely as a back up, we do not accept pull requests here (funnily it actually says that in the commit :-)) 

Ill close this and if you want I can submit a patch and get it into Koha proper, or you can, if I dont see one in a few days, I will do it

**Comment by horus68** [comment]
@ranginui this PR is a fix for the readme file not to the Koha code.
The readme file is the file displayed in github project frontpage.
Just for curiosity... the fix is just to fix the URL of koha community site!
So this PR needs to be in!

**Comment by kfischer** [comment]
This is just a copy of our main repository, the file needs to be fixed there:
http://git.koha-community.org/gitweb/?p=koha.git;a=blob;f=README.md;h=3e82a080b02f5ed6eae7fd5f59f1a6cf6cc9ea46;hb=7130d554584b7ab4f4480399f5d29a90d0aef3d6

**Comment by ranginui** [comment]
Yes, as pointed out, if we merge into the backup repo, then it will just get out of sync with the actual repository. So it needs to be fixed there. If you don't have time to send a patch, or attach one to a bug report, then I can fix it in the main repo. We accept no pull requests on github, because it is just a backup not the main repository.

So just let me know if you want to send a patch, or I can fix

**Comment by phavel** [comment]
I will not send a patch, please fix it.

**Pull request closed without merging**
